name: Demo Github 
on: [push]

jobs:
  Example-Job-01:
    name: Sample Job 1
    runs-on: self-hosted
    steps:
      # Step 1
      - run: echo "running Step 1 of Sample Job 1 triggered by ${{ github.event_name}} event."
      
      - name: Step 1 - Create a temporary artifact downloads folder
        run: mkdir downloads
      
      - name: step 2 - Add artifacts to publish to the temp folder
        run: |
          cd downloads
          date >dt
          cd ..
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: assets-for-download
          path: downloads
