name: Demo Github 
on:
  push:
    # Pattern Matched against ref/tags
    tags:
      - 'v0.0.*'

jobs:
  Example-Job-01:
    name: Sample Job 1
    runs-on: self-hosted
    steps:
      - name: Step 1 - Post to jenkins
        run: Remove-Item alias:curl
          curl -X POST "http://build:11d1bf2648c69a16254c438c81f052a867@192.168.29.51:8080/job/test/build"
